default_profile: local

base:
  service:
    host: 127.0.0.1
    port: 8011
    api_prefix: /media/v1
    reload: false

  media_client:
    base_url: http://127.0.0.1:8011/media/v1
    request_timeout_ms: 60000

  worker:
    concurrency: 1

  logging:
    log_level: DEBUG

profiles:
  local: {}
  test: {}
  prod: {}
