"""Shared LLM business keys and provider labels."""

from __future__ import annotations

AGENT_MAIN_BIZ_KEY = "agent.main"
AGENT_STATUS_SUB_AGENT_BIZ_KEY = "agent.status_sub_agent"
AGENT_MEMORY_SUB_AGENT_BIZ_KEY = "agent.memory_sub_agent"

MEMORY_EMBED_BIZ_KEY = "memory.embed"
MEMORY_QUERY_PLANNER_BIZ_KEY = "memory.query_planner"
MEMORY_RERANK_BIZ_KEY = "memory.rerank"

PROVIDER_SHARED = "shared"
PROVIDER_OPENAI = "openai"
PROVIDER_LLAMA = "llama"
PROVIDER_DEFAULT = PROVIDER_OPENAI

PROVIDER_KINDS = frozenset({PROVIDER_SHARED, PROVIDER_OPENAI, PROVIDER_LLAMA})

LLM_KIND_CHAT = "chat"
LLM_KIND_EMBEDDING = "embedding"
LLM_KIND_PLANNER = "planner"
LLM_KIND_RERANK = "rerank"
LLM_KINDS = frozenset({LLM_KIND_CHAT, LLM_KIND_EMBEDDING, LLM_KIND_PLANNER, LLM_KIND_RERANK})

RERANK_MODEL_TYPE_QWEN3_LOGIT = "qwen3_logit"
RERANK_MODEL_TYPE_CHAT_POINTWISE = "chat_pointwise"
RERANK_MODEL_TYPES = frozenset({RERANK_MODEL_TYPE_QWEN3_LOGIT, RERANK_MODEL_TYPE_CHAT_POINTWISE})
