"""Compatibility re-export for RP Module constants."""

from rpg_core.rp_module_constants import (
    RP_MODULE_DICE_NAME,
    RP_MODULE_DICE_SECTION_ID,
    RP_MODULE_DICE_SOURCE,
    RP_MODULE_DICE_TURN_SECTION_ID,
    RP_MODULE_NARRATIVE_OUTCOME_NAME,
    RP_MODULE_NARRATIVE_OUTCOME_SECTION_ID,
    RP_MODULE_NARRATIVE_OUTCOME_SOURCE,
    RP_MODULE_NARRATIVE_OUTCOME_TURN_SECTION_ID,
    RP_MODULE_SOURCE_PREFIX,
)

__all__ = [
    "RP_MODULE_DICE_NAME",
    "RP_MODULE_DICE_SECTION_ID",
    "RP_MODULE_DICE_SOURCE",
    "RP_MODULE_DICE_TURN_SECTION_ID",
    "RP_MODULE_NARRATIVE_OUTCOME_NAME",
    "RP_MODULE_NARRATIVE_OUTCOME_SECTION_ID",
    "RP_MODULE_NARRATIVE_OUTCOME_SOURCE",
    "RP_MODULE_NARRATIVE_OUTCOME_TURN_SECTION_ID",
    "RP_MODULE_SOURCE_PREFIX",
]
