"""Compatibility re-export for RP Module constants."""

from rpg_core.rp_module_constants import (
    RP_MODULE_DICE_NAME,
    RP_MODULE_DICE_SECTION_ID,
    RP_MODULE_DICE_SOURCE,
    RP_MODULE_SOURCE_PREFIX,
    RP_MODULE_TEXT_OUTPUT_FORMAT_NAME,
    RP_MODULE_TEXT_OUTPUT_FORMAT_SECTION_ID,
    RP_MODULE_TEXT_OUTPUT_FORMAT_SOURCE,
    RP_OUTPUT_ATTR_CHARACTER_NAME,
    RP_OUTPUT_FORMAT_XML_TAGS,
    RP_OUTPUT_TAG_CHARACTER,
    RP_OUTPUT_TAG_NARRATION,
)

__all__ = [
    "RP_MODULE_DICE_NAME",
    "RP_MODULE_DICE_SECTION_ID",
    "RP_MODULE_DICE_SOURCE",
    "RP_MODULE_SOURCE_PREFIX",
    "RP_MODULE_TEXT_OUTPUT_FORMAT_NAME",
    "RP_MODULE_TEXT_OUTPUT_FORMAT_SECTION_ID",
    "RP_MODULE_TEXT_OUTPUT_FORMAT_SOURCE",
    "RP_OUTPUT_ATTR_CHARACTER_NAME",
    "RP_OUTPUT_FORMAT_XML_TAGS",
    "RP_OUTPUT_TAG_CHARACTER",
    "RP_OUTPUT_TAG_NARRATION",
]
