TTS_ERROR_CODE_GENERIC = "TTS_ERROR"
TTS_ERROR_CODE_INVALID_AUDIO = "TTS_INVALID_AUDIO"
TTS_ERROR_CODE_SOURCE_CHANGED = "TTS_SOURCE_CHANGED"
TTS_ERROR_CODE_GENERATION_FAILED = "TTS_GENERATION_FAILED"
TTS_ERROR_CODE_WORKER_ERROR = "TTS_WORKER_ERROR"
TTS_ERROR_CODE_JOB_INTERRUPTED = "TTS_JOB_INTERRUPTED"
TTS_ERROR_CODE_CACHE_MISSING = "TTS_CACHE_MISSING"


class TTSError(Exception):
    error_code = TTS_ERROR_CODE_GENERIC


class TTSInvalidAudioError(TTSError):
    error_code = TTS_ERROR_CODE_INVALID_AUDIO


class TTSSourceChangedError(TTSError):
    error_code = TTS_ERROR_CODE_SOURCE_CHANGED
